import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { toast } from "react-hot-toast";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Modal from "../components/Modal";

const Home: NextPage = () => {
  return (
    <div className="text-accent min-h-screen flex flex-col bg-primary">
      <Head>
        <title>Decisive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex flex-col items-center">
        <Image src="/decide.svg" width={300} height={300} />
        <section className="flex flex-col">
          <div className="-mt-10 font-bold form-control w-full max-w-xs">
            <label className="label">
              <span className="label-text">Enter your choices</span>
            </label>
            <input
              type="text"
              placeholder="Your choices go here"
              className="input input-ghost focus:outline-accent font-normal w-full max-w-xs"
            />
            <label className="label">
              <span className="label-text-alt text-accent italic">
                Separate it with spaces!
              </span>
            </label>
          </div>
          <button
            className="mt-3 btn btn-outline hover:bg-accent"
            onClick={() => {
              document.getElementById("modal")?.click();
            }}
          >
            choose
          </button>
        </section>
      </main>
      <Footer />
      {/* hidden modal */}
      <Modal content="The quick brown fox jumps over the lazy dog" />
    </div>
  );
};

export default Home;
