import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Toast, toast } from "react-hot-toast";
import { useState, useEffect, ChangeEvent } from "react";
import { useIdle } from "react-use";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Modal from "../components/Modal";

const Home: NextPage = () => {
  const isIdle = useIdle(10000);
  const [inputValue, setInputValue] = useState("");
  const [modalContent, setModalContent] = useState("");
  const onInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  };

  const onRandomize = (t: Toast) => {
    const randomChoices: string[] = [
      "Buy now, Buy later",
      "Go out alone, Go out with friends",
      "Workout now, Workout later, Workout tomorrow",
      "Take a nap, Continue studying",
      "React, Vue, Svelte, Angular, Solid",
      "Node, Laravel, SpringBoot",
    ];

    const choice =
      randomChoices[Math.floor(Math.random() * randomChoices.length)];

    setInputValue(choice);
    toast.dismiss(t.id);
  };

  const onChoose = () => {
    const chooseBtn = document.querySelector("#choose-btn");
    const choices = inputValue.split(",");

    chooseBtn?.classList.add("loading");

    const result = new Promise((resolve, reject) => {
      const res = choices[Math.floor(Math.random() * choices.length)];

      setTimeout(() => {
        if (choices.length === 1)
          reject(new Error("Please use a comma to separate your choices!"));
        if (res) resolve(res);
      }, 1500);
    });

    result
      .then(
        (value) => {
          setModalContent(`${value}`);
          document.getElementById("modal")?.click();
        },
        (error) => {
          setModalContent(`${error}`);
          document.getElementById("modal")?.click();
        }
      )
      .finally(() => {
        chooseBtn?.classList.remove("loading");
      });
  };

  useEffect(() => {
    if (isIdle)
      toast((t) => (
        <span>
          🤔 Still can't decide?&nbsp;
          <button className="btn btn-xs" onClick={() => onRandomize(t)}>
            Randomize
          </button>
        </span>
      ));
  }, [isIdle]);

  return (
    <div className="text-accent min-h-screen flex flex-col bg-primary">
      <Head>
        <title>Decisive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex flex-col items-center">
        <Image src="/decide.svg" width={300} height={300} />
        <section className="flex flex-col">
          <div className="-mt-10 font-bold form-control w-full max-w-xs">
            <label className="label">
              <span className="label-text">Enter your choices</span>
            </label>
            <input
              type="text"
              placeholder="Your choices go here"
              className="input input-ghost focus:outline-accent font-normal w-full max-w-xs"
              spellCheck={false}
              value={inputValue}
              onChange={onInputChange}
            />
            <label className="label">
              <span className="label-text-alt text-accent italic">
                Separate it with comma!
              </span>
            </label>
          </div>
          <button
            id="choose-btn"
            className="mt-3 btn btn-outline hover:bg-accent"
            onClick={onChoose}
          >
            choose
          </button>
        </section>
      </main>
      <Footer />
      {/* hidden modal */}
      <Modal content={modalContent} />
    </div>
  );
};

export default Home;
